apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payments
  description: payments service
  annotations:
    github.com/project-slug: entr0pian/payments
spec:
  type: service
  lifecycle: experimental
  owner: payments-team
